# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Gdayx 2014"
email: "gbglima@gmail.com"
description: "GdayxLima 2014"
baseurl: ""
url: "http://gdayx.pe"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-41385112-1"
googleAnalyticsSiteUrl: "gdayx.pe"


# Organizer Info
organizerName: GBG Lima"
organizerAlternateName: "Google Business Group Lima"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdglima@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdax.pe"

# Head
metaKeywords: "event, gbg , gdayx, google, business"
#twitterAccount: "@Dgbgperu"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Documents
c4pUrl: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform"
c4sponsorsUrl: "/assets/devfest-midiakit-final.pdf"
c4sponsorsUrlEn: "/assets/devfest-midiakit-final-en.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Expositores"}
 # - {permalink: "/team/", text: "Time"}
 # - {permalink: "/logistics/", text: "Logistica"}
 # - {link: "https://developers.google.com", text: "Desenvolvedores"}
 # bottomNavigationLinks:
 # - {link: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform", text: "Seja um palestrante"}
 # rightNavigationButtons:
 #- {link: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform", text: "Seja um palestrante"}

# Hero Block
heroTitle: "GdayxLima <typeout> 2014"
eventDate: "13  de Diciembre de 2014"
typeoutTextValues: '"Emprendimiento", "Empoderamiento", "Negocios"'
heroButtons:
# - {url: "https://docs.google.com/forms/d/1egw-Kjo86PivWiu6yUwUW0tyY9jkNTiwU3nFzWK24Fk/viewform", text: "Seja um palestrante"}
 

# About Block
aboutTitle: "Acerca del Gdayx"
aboutBlock:
 - {title: "Conferencias", image: "conference.jpg", text: "El evento principal de GBG's" }
 - {title: "Talleres", image: "workshop.jpg", text: "" }

# Statistic Block
statisticBlock:
 - {count: "20", specialCharacter: "+", info: "horas", detail: "de pura tecnologia Google"}
 #- {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "2", specialCharacter: "", info: "sesiones en paralelo", detail: "interactivas"}

# Latest News Block
latestNewsTitle: "Últimas Notícias"

# Rockstar Speakers Block
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar"
rockstarSpeakersButtonText: "Ver +Expositores"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Fia Data"
eventLocationLink: ""
eventStreetAddress: "Av. La Fontana 1250 Urb. Sta. Patricia 2da Etapa La Molina"
eventAddressLocality: "Lima"
eventAddressLocalityRegion: "L"
eventPostalCode: ""
eventAddressCountry: "Perú"
eventStartTime: "2014-12-13T8:00"
eventDoorTime: "09:00"
eventEndTime: "2014-12-13T18:00"
eventPlaceCoordinates: "-12.0723315,-76.94166519999999"
mapCenterCoordinates: "-12.0723315,-76.94166519999999"
mapMobileCenterCoordinates: "-12.0723315,-76.94166519999999"

# # Venue Block
# venueBlockTitle: "Venue"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# # Tweets Feed Block
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: ""
partnersC4sponsorsButtonEn: ""

# # Organizers Block
# organizersTitle: "Organizers"

# # Subscribe Block
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"


# Buy Tickets Block
ticketsTitle: "Inscribete"

ticketsOffers:
-
  name: "Believe in the Force"
  price: ""
  priceCurrency: ""
  buyButtonLink: ""
  buyButtonText: ""
  # additionalInfo: "Preço válido até 15/10/2014"
  validFrom: "2014-12-01T00:00"
  validThrough: "2014-12-12T23:59"
  soldOut: true
  soldOutText: ""


# Footer
socialLinks:
 - {link: "https://plus.google.com/+GdgspOrg", icon: "google-plus"}
 
footerBlocks:
 -
  title: "Grupos"
  links:
   - {link: "https://plus.google.com/103607234084788626166/posts", text: "GBG Lima"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gdglima@gmail.com", text: "gdglima@gmail.com"}


# Blog
blogTitle: "Últimas novidades"
blogCommentsEnabled: true
discusShortName: "gdayx"

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "Sobre nosotros"
aboutUs: "Comunidad de Negocios con productos de Google - GBG Lima - Conecta Informa e Inspira"

# Logistics Find Way Block
findWayTitle: ""
logisticsMapCenterCoordinates: ""
logisticsMapMobileCenterCoordinates: ""

# # Logistics Direction Details Block
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards: 
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    - 
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
