# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2014"
email: "limadevfest@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "http://limadevfest.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-55838618-1"
googleAnalyticsSiteUrl: "limadevfest.com"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/blog/", text: "blog"}
 - {permalink: "/speakers/", text: "Expositores"}
 - {permalink: "/schedule/", text: "Agenda"}
rightNavigationButtons:
 - {link: "http://goo.gl/zFEg3u", text: "Participa en modo fiesta en G+"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "Lima DevFest okey Google  <typeout> "
eventDate: "08 Noviembre, 2014"
typeoutTextValues: '"", "Ir al LimaDevFest", "Obtener una entrada"'
typeoutFallback: "Season"
heroButtons:
 - {permalink: "/#tickets", text: "Obten tu entrada"}
 - {link: "http://goo.gl/zFEg3u", text: "Interactua en G+"}


# About Block
aboutTitle: "Acerca Lima DevFest"
aboutBlock:
 - {title: "Conferencia", image: "conference.jpg", text: "Presentaremos las ultimas novedades del google io" }
 - {title: "Talleres", image: "workshop.jpg", text: "Taller full practico" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "10", specialCharacter: "+", info: "horas", detail: "de tecnología google"}
 - {count: "10", specialCharacter: "+", info: "expositores", detail: "de diferentes ciudades"}
 - {count: "3", specialCharacter: "", info: "sesiones", detail: "en paralelo"}

# Latest News Block
latestNewsTitle: "Ultimas novedades"


#Organizer GDG
organizerGDGImage : "rockstar-speakers.jpg"
organizerGDGCount : 3
organizerGDGTitle : "Gracias al apoyo de las comunidades"
organizerGDGButtonText : "+siganos en nuestras redes"





# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Universidad Ricardo Palma"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Av. Benavides 5440 - Santiago de Surco"
eventAddressLocality: "URP"
eventAddressLocalityRegion: "URP"
eventPostalCode: "79000"
eventAddressCountry: "Lima"
eventStartTime: "2014-11-08T08:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-08T18:00"
eventPlaceCoordinates: "-12.132417, -76.97978760000001"
mapCenterCoordinates: "-12.132417, -76.97978760000001"
mapMobileCenterCoordinates: "-12.132417, -76.97978760000001"


# Venue Block
venueBlockTitle: "Auditorio"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditorio A"
venueFeatures: ["3 salones", "", ""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ¡Interactúa con nosotros!
twitterHashTag: "ldf14"


# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"


# Tickets Block
ticketsTitle: "Entradas"
ticketsInfo: "Acceso a todas las conferencias y talleres."
ticketsOffers:
 -
  name: "LimaDevFest"
  price: "Gratis"
  priceCurrency: 
  ticketsNumber: "200"
  ribbon: 
  buyButtonLink: "https://www.eventbrite.com/e/lima-devfest-2014-tickets-13735189321"
  buyButtonText: "Obten tu entrada"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-08T23:59"

# Footer
socialLinks:
 - {link: "", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=LimaDevFest", icon: "twitter"}
 - {link: "", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:limadevfest@gmail.com", text: "limadevfest@gmail.com"}

# Blog
blogTitle: "Novedades"
blogCommentsEnabled: true
discusShortName: "limadevfest"

# Speakers List Block
showSessions: false
speakerTitle: "#limadevfest"
speakerRows:
 - {title: "Programa", image: "hackathon-2.png", details: "Estamos construyendo el programa para tu máximo beneficio. Gracias por la espera #limadevfest."}



# Team Block
teamBlockTitle: "Acerca de nosotros"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
